### PR TITLE
only download etcd archive if it does not exist

### PR DESCRIPTION
**Pull request by ghouscht**
Simple check to download the etcd archive only if it does not exist alredy - fixes issue #73

### CODE REVIEW

**Comment by dlipovetsky** [comment]
Thanks @ghouscht!

I want to note this introduces a new issue: if the archive is corrupt or incomplete, etcdadm will not download it again, and the user needs to delete it. We can address that issue by verifying the archive using the published key. I'll file a separate PR.

/approve
/lgtm

Let's wait a couple of days for comments. @moshloop and @justinsb .
/hold

**Comment by ghouscht** [comment]
> I want to note this introduces a new issue: if the archive is corrupt or incomplete, etcdadm will not download it again, and the user needs to delete it. We can address that issue by verifying the archive using the published key. I'll file a separate PR.

Good note! This should be done anyway. I could have a look at it in the next few days and adopt my PR if this is ok.

**Comment by dlipovetsky** [comment]
@ghouscht I think we can merge this and address my comment separately. Thanks for this 

/hold cancel

**Comment by dlipovetsky** [comment]
> docs/USECASES.md: no newline at the end of file

Sorry, an unrelated error causes the test job to fail. Fixing momentarily.

**Pull request merged**
