### PR TITLE
remove vendor

### PR DESCRIPTION
**Pull request by chuckha**
Using go.mod vendor is no longer required. There was one minor change to the go.sum file.

Signed-off-by: Chuck Ha <chuckh@vmware.com>

### CODE REVIEW

**Comment by dlipovetsky** [comment]
@chuckha  Is it correct to say that the `vendor` directory is already being ignored if using go 1.12, so this change just removes that directory?

**Comment by chuckha** [comment]
if this is outside the go path then by default, yes, go will ignore vendor

**Pull request merged**
