### PR TITLE
Add automatic release tagging for etcd-manager

### PR DESCRIPTION
**Pull request by hakman**
Similar to https://github.com/kubernetes/kops/pull/12805.

/cc @justinsb @johngmyers @olemarkus @rifelpet

### CODE REVIEW

**Comment by justinsb** [comment]
Looks great - thanks @hakman 

Who figured out that regex? :-)

/approve
/lgtm

**Comment by hakman** [comment]
> Who figured out that regex? :-)

That was @johngmyers. It is an adaptation on what he did for kOps. 😄 
Updated the day to today, keep it simple later.

**Review by rifelpet — APPROVED** [review]

**Comment by hakman** [comment]
Looks like we have a winner:
https://storage.googleapis.com/kubernetes-jenkins/logs/etcdadm-postsubmit-push-to-staging/1521481690688524288/artifacts/build.log

**Comment by hakman** [comment]
Promoted in https://github.com/kubernetes/k8s.io/pull/3695.

**Pull request merged**
