### PR TITLE
Add etcd-manager under etcd-manager/ subdirectory

### PR DESCRIPTION
**Pull request by justinsb**
As discussed in office hours, adding etcd-manager in a subdirectory to enable the projects to converge.

### CODE REVIEW

**Comment by justinsb** [comment]
(I have asked the helpdesk for a hint as to which commits are making the CLA bot unhappy)

**Comment by justinsb** [comment]
I cracked the code @dlipovetsky - clabot is happy :-)

**Comment by justinsb** [comment]
@dlipovetsky I think this is green (with a few exclusions, admittedly!)

**Comment by dlipovetsky** [comment]
image

:laughing: 

Thank you for seeing this through, @justinsb!

/lgtm

**Comment by dlipovetsky** [comment]
I wonder why there are rebase conflicts...

**Comment by justinsb** [comment]
I think/hope the rebase conflicts were from before I figured out the correct procedure!  If not I guess it won't merge, so ....

/hold cancel

**Pull request merged**
