### PR TITLE
Support linux other arch

### LINKED ISSUE #221: Factor in cpu arch
The build was successful, however, running init shows it trying to use the amd64 bundle on arm
```
etcdadm init
INFO[0000] [install] Artifact not found in cache. Trying to fetch from upstream: https://github.com/coreos/etcd/releases/download
INFO[0000] [install] Downloading & installing etcd https://github.com/coreos/etcd/releases/download from 3.4.13 to /var/cache/etcdadm/etcd/v3.4.13
INFO[0000] [install] downloading etcd from https://github.com/coreos/etcd/releases/download/v3.4.13/etcd-v3.4.13-linux-amd64.tar.gz to /var/cache/etcdadm/etcd/v3.4.13/etcd-v3.4.13-linux-amd64.tar.gz
######################################################################## 100.0%##=O#- #
INFO[0001] [install] extracting etcd archive /var/cache/etcdadm/etcd/v3.4.13/etcd-v3.4.13-linux-amd64.tar.gz to /tmp/etcd638248988
INFO[0002] [install] verifying etcd 3.4.13 is installed in /opt/bin/
FATA[0002] [install] Error: fork/exec /opt/bin/etcd: exec format error
```

### PR DESCRIPTION
**Pull request by pytimer**
Fixes #221

### CODE REVIEW

**Comment by justinsb** [comment]
This LGTM also, but it's in the etcdadm areas of the code.

/assign @dlipovetsky 

/lgtm

**Comment by dlipovetsky** [comment]
Thanks @pytimer!

This works under the assumption that etcdadm runs on the same machine as the etcd member it initializes.
 
/lgtm

**Comment by dlipovetsky** [comment]
Given https://github.com/kubernetes-sigs/etcdadm/issues/221, let's note this in the release notes:

```
To run on an architecture other than amd64, you must add the `ETCD_UNSUPPORTED_ARCH=<architecture>` to the etcd systemd service environment file, /etc/etcd/etcd.env"
```

**Comment by pytimer** [comment]
@dlipovetsky Could we write `ETCD_UNSUPPORTED_ARCH` environment in [service.WriteEnvironmentFile()](https://github.com/kubernetes-sigs/etcdadm/blob/master/cmd/init.go#L99) if not amd64, avoid to someone forget it when run etcdadm on the other arch?

**Comment by dlipovetsky** [comment]
> @dlipovetsky Could we write `ETCD_UNSUPPORTED_ARCH` environment in [service.WriteEnvironmentFile()](https://github.com/kubernetes-sigs/etcdadm/blob/master/cmd/init.go#L99) if not amd64, avoid to someone forget it when run etcdadm on the other arch?

Maybe. Is that env var accepted across all etcd v3.x versions?

**Comment by pytimer** [comment]
> > @dlipovetsky Could we write `ETCD_UNSUPPORTED_ARCH` environment in [service.WriteEnvironmentFile()](https://github.com/kubernetes-sigs/etcdadm/blob/master/cmd/init.go#L99) if not amd64, avoid to someone forget it when run etcdadm on the other arch?
> 
> Maybe. Is that env var accepted across all etcd v3.x versions?

I read the etcd docs for v3.3~v3.5, `ETCD_UNSUPPORTED_ARCH` env supported. You can check docs https://etcd.io/docs/v3.5/op-guide/supported-platform/ to verify it again.

**Comment by dlipovetsky** [comment]
> I read the etcd docs for v3.3~v3.5, ETCD_UNSUPPORTED_ARCH env supported. You can check docs https://etcd.io/docs/v3.5/op-guide/supported-platform/ to verify it again.

I agree, then, that etcdadm can write this.

**Comment by pytimer** [comment]
> > I read the etcd docs for v3.3~v3.5, ETCD_UNSUPPORTED_ARCH env supported. You can check docs https://etcd.io/docs/v3.5/op-guide/supported-platform/ to verify it again.
> 
> I agree, then, that etcdadm can write this.

OK. I will commit code soon.

**Comment by dlipovetsky** [comment]
We can address the `ETCD_UNSUPPORTED_ARCH` as a separate PR.

/lgtm

**Pull request merged**
