### PR TITLE
include verification scripts for CI / PR verification

### PR DESCRIPTION
**Pull request by neolit123**
similar tooling are already in place for the following repos:
- k/kubeadm
- k-sigs/cluster-api-bootstrap-provider-kubeadm
- k-sigs/cluster-api-provider-docker

fixes: https://github.com/kubernetes-sigs/etcdadm/issues/109

/priority important-longterm
/kind feature

### CODE REVIEW

**Comment by neolit123** [comment]
/assign @dlipovetsky 

this is ready for review.
included boiler plate changes.

**Comment by neolit123** [comment]
PR for test-infra is on hold here: https://github.com/kubernetes/test-infra/pull/13311

**Comment by dlipovetsky** [comment]
@neolit123 Thanks very much!

I see that `hack/verify-all.sh` is the entrypoint for the pre-submit tests, How should developers run this locally? I can add this to the Makefile, or add a git pre-commit hook. What does kubeadm do? (IIRC, since it's in k/k for now, it's in the k/k Makefile)

I will file a PR to fix the FIXMEs and TODOs.

/lgtm
/approve

**Comment by neolit123** [comment]
> I see that hack/verify-all.sh is the entrypoint for the pre-submit tests, How should developers run this locally? I can add this to the Makefile, or add a git pre-commit hook. What does kubeadm do? (IIRC, since it's in k/k for now, it's in the k/k Makefile)

these come from k/kubeadm -> /kinder.
to run locally one can do /hack/verify-all.sh

adding a Makefile rule for that can work.

**Comment by neolit123** [comment]
forgot to remove the `hold` on the test-infra PR...
https://github.com/kubernetes/test-infra/pull/13311

it's merging now and after that there should be a new dashboard here:
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-all

with etcdadm/pr-verify.

**Pull request merged**
