### PR TITLE
#100 Release binary artifiacts

### PR DESCRIPTION
**Pull request by moshloop**
You can see the build here:

https://travis-ci.org/moshloop/etcdadm/builds/529865182

And the result here:

https://github.com/moshloop/etcdadm/releases/tag/v0.1.8

There is still a little work required to fix the ldflags but this should give the basic idea

### CODE REVIEW

**Comment by dlipovetsky** [comment]
@moshloop As you said offline, the go module changes should probably move to a separate PR.

**Comment by moshloop** [comment]
@dlipovetsky see https://github.com/moshloop/etcdadm/releases/tag/v1.11

**Comment by dlipovetsky** [comment]
Thank you @moshloop!

/lgtm
/approve

**Pull request merged**
