### PR TITLE
Merge in upstream changes to etcd-manager

### PR DESCRIPTION
**Pull request by justinsb**

### CODE REVIEW

**Comment by justinsb** [comment]
Changelist:

```
e2a80a8c Release notes for 3.0.20201117
c9e68871 Fix build on case-insensitive file systems (MacOS)
ae536008 Switch the cloudbuild docker image, locking to 2.2.0
e038d60d Set AltNames on server certificates
6daca9a0 govet: Fix a log message
9a8f17bf Build base image by raw expansion of deb packages
46977da9 Update vendor for kops 1.19.0-beta.1
22d9df56 Update etcd client
be637923 Add support for MountSensitive
8b3172d0 Update kops to pick up AllowReauth Openstack fix
9ae4a0c7 Added full cinder ID to candidateDeviceNodes
2dfa413a Push multi-arch compatible with DockerHub
6d47b43c Add back support for etcd 2.2.1
e38c45db Add ETCD_UNSUPPORTED_ARCH=arm64 env var
c12682a7 Add build targets for ARM64
0c08b57f Update Bazel rules
84f22417 Support for arm64
1acc15be Revert "Move from debian-hyperkube-base to debian-base"
aac22ec3 Revert "Switch to l.gcr.io/google/debian10"
48fe45f3 Revert "Update WORKSPACE"
ce8a4bd8 Revert "Update BUILD"
608db56c feat(docs): add documentation about handling bad commands in storage
b9c533bc feat(etcd-manager-ctl): use backupname to delete backup instead of timestamp
30d0d4e5 when doing discovery ignore AZ
a968992b Update BUILD
d5b3e613 Update WORKSPACE
92bef6f5 Switch to l.gcr.io/google/debian10
81ac26c0 Add support for etcd 3.4.13
```

Upstream PRs:

https://github.com/kopeio/etcd-manager/pulls/364
https://github.com/kopeio/etcd-manager/pulls/360
https://github.com/kopeio/etcd-manager/pulls/362
https://github.com/kopeio/etcd-manager/pulls/361
https://github.com/kopeio/etcd-manager/pulls/363
https://github.com/kopeio/etcd-manager/pulls/355
https://github.com/kopeio/etcd-manager/pulls/347
https://github.com/kopeio/etcd-manager/pulls/352
https://github.com/kopeio/etcd-manager/pulls/358
https://github.com/kopeio/etcd-manager/pulls/351
https://github.com/kopeio/etcd-manager/pulls/334
https://github.com/kopeio/etcd-manager/pulls/345
https://github.com/kopeio/etcd-manager/pulls/344

**Comment by sudoforge** [comment]
I've signed the CLA. @justinsb I think you'll need to `git commit --amend --no-edit && git push --force` in order to re-trigger the check.

**Comment by justinsb** [comment]
Thanks for taking care of the CLA @sudoforge 

With a few other fixes to the verify job, looks like we are now passing tests cc @dlipovetsky

**Pull request merged**
